### ISSUE TITLE
into_nalgebra failed to work for 2d array with one row

### ISSUE THREAD

**Issue by qqlearn123** [rust-cv/nshare#13]
The following code section will panic:
```
let a = array!([[1.2, 2.3, 5.5]]);
let a2 = a.into_nalgebra();
```

**Comment by vadixidav** [comment]
@qqlearn123 I tried this with my latest changes in #17 and this seems to work, but you may have an issue with your array or may have indexed starting at 1 instead of 0. Notably, `ndarray::array` should be used like `array![[1.2, 2.3, 5.5]]`, and not like `array!([[1.2, 2.3, 5.5]])`. If you use it with parentheses, it will create three axes (the parentheses are treated like square brackets, and it is confusing). Just in case I added a test in #17 (see [here](https://github.com/rust-cv/nshare/pull/17/files#diff-0d78f16e270a151477341396dcec8adae581cb8d531ed6eb2d91ebb152bd0fdfR4)) that specifically tests the case of a one row array just to make sure it works.
